@startuml enviroment
skinparam folder {
	backgroundColor<<OUTPUT>> aquamarine
}
folder "_build_/" {
  frame "Makefile" {
    [top]
  }
}
folder "add/" {
  frame "add-Makefile" {
    [add] <.. [top] #blue
  }
}
folder "subtract/" {
  frame "subtract-Makefile" {
    [subtract] <.. [top] #blue
  }
}
folder "main/" {
  frame "main-Makefile" {
    [main] <.. [top] #blue
  }
}
folder "multiply/" {
  frame "multiply-Makefile" {
    [multiply] <.. [top] #blue
  }
}
folder "divide/" {
  frame "divide-Makefile" {
    [divide] <.. [top] #blue
  }
}
folder "_build_/" {
  frame "MakefileRule.mk" {
    [top] .. [TARGETS] #white
    [add] --> [TARGETS]
    [subtract] --> [TARGETS]
    [multiply] --> [TARGETS]
    [divide] --> [TARGETS]
  }
}
folder "_build_/obj/" <<OUTPUT>> {
  frame "add.a" {
    frame "add.o" {
      [add()] <<-- [add] #black
    }
  }
  frame "subtract.a" {
    frame "subtract.o" {
      [subtract()] <<-- [subtract] #black
    }
  }
  frame "multiply.a" {
    frame "multiply.o" {
      [multiply()] <<-- [multiply] #black
    }
  }
  frame "divide.a" {
    frame "divide.o" {
      [divide()] <<-- [divide] #black
    }
  }
  frame "main.a" {
    frame "main.o" {
      [main()] <<-- [main] #black
    }
  }
}
folder "_build_/out/" <<OUTPUT>> {
  frame "main.exe" {
    [program] <<-- [main()] #black
    [program] <<-- [add()] #black
    [program] <<-- [subtract()] #black
    [program] <<-- [multiply()] #black
    [program] <<-- [divide()] #black
  }
}
folder "_build_/" {
    frame "MakefileTool.mk" {
      [TOOLS]
      [TARGETS] ..> [TOOLS]
    }
}
    frame "MakefileOption.mk" {
      [OPTION]
    }
    frame "MakefileDefine.mk" {
      [DEFINE]
    }
    frame "MakefileInclude.mk" {
      [INCLUDE]
    }
    frame "MakefileLibs.mk" {
      [LIBS]
    }
folder "tool-directory/" {
  frame "cc.exe" {
    [compiler]
    [TOOLS] ..> [compiler]
    [compiler] <.. [OPTION]
    [compiler] <.. [DEFINE]
    [compiler] <.. [INCLUDE]
  }
  frame "ar.exe" {
    [archiver]
    [TOOLS] ..> [archiver]
  }
  frame "ld.exe" {
    [linker]
    [TOOLS] ..> [linker]
    [linker] <.. [LIBS]
  }
}
folder "_build_/" {
    frame "MakefileOutput.mk" {
      [OUTPUTS] #aquamarine
      [TOOLS] .. [OUTPUTS] #white
      [OUTPUTS] <.. [compiler] #black
      [OUTPUTS] <.. [archiver] #black
      [OUTPUTS] <.. [linker] #black
    }
}
@enduml